version: '3.9'

services:
  app:
    build: ./docker/app
    volumes:
      - ./src:/app

  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./src/:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: authenticate
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
