version: '3.9'

services:
  app:
    build:
      context: ./docker/app
    ports:
      - '80:80'
      - '5173:5173'
    volumes:
      - ./src/:/var/www/html
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf

  db:
    build: ./docker/db
    volumes:
      - db-store:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - target: 8025
        published: ${MAILHOG_PUBLISHED_PORT:-8025}
        protocol: tcp
        mode: host

volumes:
  db-store:
