name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0.30
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.9'
          extensions: mbstring, intl
          coverage: none
      - name: Composer install
        run: |
          composer install --ignore-platform-reqs
      - name: NPM Build
        run: |
          npm install
          npm run build
      - name: Copy env.example
        run: cp .env.testing .env
      - name: Encryption Key generate
        run: php artisan key:generate --env=testing
      - name: Run Migrate
        env:
          DB_HOST: 127.0.0.1
        run: php artisan migrate --env=testing
      - name: Run Pest
        env:
          DB_HOST: 127.0.0.1
        run: ./vendor/bin/pest
      - name: Execute phpstan
        run: |
          ./vendor/bin/phpstan analyse

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: NPM install
        run: npm install
